spring:
  mvc:
    static-path-pattern: /resources/**
    view:
      prefix: /WEB-INF/pages/
      suffix: .jsp
    
  datasource:
    url: 'jdbc:h2:mem:devdb'
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: 'true'
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    
 
    
server:
  port: '6010'
  
management:
  security:
    enabled=false
    
    
    
    
    
user:
  messages:
    profile:
      save: Congratulations Dear {}, Your profile has been successfully created on {}.
      failed-error: Dear {}, We are sorry to inform you that profile creation process could not processed on {}.
