spring:
  mvc:
    static-path-pattern: /resources/**
    view:
      prefix: /WEB-INF/pages/
      suffix: .jsp
    
  datasource:
    password: '!@123Rahul'
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: bhara2dt_rahul
    url: jdbc:mysql://119.18.54.126:3306/bhara2dt_uat?useSSL=false&allowPublicKeyRetrieval=true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    
 
    
server:
  port: '9012'

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL:http://172.17.0.2:8761/eureka}
  instance:
    prefer-ip-address: true
      
management:
  security:
    enabled=false
